// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Graeme.Dowie.Practice
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Sealink Homepage")]
    public partial class SealinkHomepageFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Sealink.Homepage.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Sealink Homepage", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 3
#line 4
 testRunner.Given("user has visited the Sealink Homepage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Top Navigation is visible")]
        [NUnit.Framework.TestCaseAttribute("Book", null)]
        [NUnit.Framework.TestCaseAttribute("Timetables and fares", null)]
        [NUnit.Framework.TestCaseAttribute("Destinations", null)]
        [NUnit.Framework.TestCaseAttribute("Travelling with us", null)]
        public virtual void TopNavigationIsVisible(string topNavMenu, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Top Navigation is visible", exampleTags);
#line 6
this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line 7
 testRunner.Then(string.Format("user should see the top navigation menu {0}", topNavMenu), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Footer Menu is visible")]
        [NUnit.Framework.TestCaseAttribute("Book", null)]
        [NUnit.Framework.TestCaseAttribute("Booking informtation", null)]
        [NUnit.Framework.TestCaseAttribute("Travel alerts", null)]
        [NUnit.Framework.TestCaseAttribute("Manage your booking", null)]
        [NUnit.Framework.TestCaseAttribute("Timetables", null)]
        [NUnit.Framework.TestCaseAttribute("Waiheke timetables & fares", null)]
        [NUnit.Framework.TestCaseAttribute("Great Barrier timetables & fares", null)]
        [NUnit.Framework.TestCaseAttribute("Rakino timetable & fares", null)]
        [NUnit.Framework.TestCaseAttribute("Destinations", null)]
        [NUnit.Framework.TestCaseAttribute("Discover Waiheke", null)]
        [NUnit.Framework.TestCaseAttribute("Discover Great Barrier", null)]
        [NUnit.Framework.TestCaseAttribute("Discover Rakino", null)]
        [NUnit.Framework.TestCaseAttribute("Discover Pine Harbour", null)]
        [NUnit.Framework.TestCaseAttribute("Travelling with us", null)]
        [NUnit.Framework.TestCaseAttribute("Our Ferries", null)]
        [NUnit.Framework.TestCaseAttribute("Delays & cancellations", null)]
        [NUnit.Framework.TestCaseAttribute("Dangerous goods", null)]
        [NUnit.Framework.TestCaseAttribute("Our ferry terminals", null)]
        [NUnit.Framework.TestCaseAttribute("Onboard facilities", null)]
        [NUnit.Framework.TestCaseAttribute("Baggage, bikes & pets", null)]
        [NUnit.Framework.TestCaseAttribute("Company Information", null)]
        [NUnit.Framework.TestCaseAttribute("About us", null)]
        [NUnit.Framework.TestCaseAttribute("Work for us", null)]
        [NUnit.Framework.TestCaseAttribute("Terms & conditions", null)]
        [NUnit.Framework.TestCaseAttribute("Feedback", null)]
        [NUnit.Framework.TestCaseAttribute("Privacy policy", null)]
        [NUnit.Framework.TestCaseAttribute("Sponsorship", null)]
        public virtual void FooterMenuIsVisible(string footMenu, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Footer Menu is visible", exampleTags);
#line 16
this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line 17
 testRunner.Then(string.Format("user should be able to see the footer menu {0}", footMenu), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("User clicks on the booking form dropdown then all options should be visible")]
        [NUnit.Framework.TestCaseAttribute("Auckland", null)]
        [NUnit.Framework.TestCaseAttribute("Waiheke", null)]
        [NUnit.Framework.TestCaseAttribute("Waiheke", null)]
        [NUnit.Framework.TestCaseAttribute("Auckland", null)]
        [NUnit.Framework.TestCaseAttribute("Auckland", null)]
        [NUnit.Framework.TestCaseAttribute("Great Barrier", null)]
        [NUnit.Framework.TestCaseAttribute("Great Barrier", null)]
        [NUnit.Framework.TestCaseAttribute("Auckland", null)]
        public virtual void UserClicksOnTheBookingFormDropdownThenAllOptionsShouldBeVisible(string bookDestination, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User clicks on the booking form dropdown then all options should be visible", exampleTags);
#line 50
this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line 51
 testRunner.When("clicks on the where are you going dropdown", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 52
 testRunner.Then(string.Format("all booking destinations should be visible {0}", bookDestination), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
